# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "usbhid" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
  # Needed for SD card reader to work.
  boot.extraModprobeConfig = ''
  options sdhci debug_quirks=0x40
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/082428f7-9e1c-401d-bf58-ec3397b09690";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ff7e036e-535c-475e-8d82-442db440a850";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2860-11F4";
      fsType = "vfat";
    };

  # Configure swap for hibernate to disk. Swappiness is set low so that it's mainly for
  # hibernation purposes.
  swapDevices = [ { device = "/var/cache/swap/swapfile"; } ];
  boot.resumeDevice = "/dev/disk/by-label/nixos";
  boot.kernelParams = [ "resume_offset=1378304" ];
  boot.kernel.sysctl = { "vm.swappiness" = 10; };

  nix.maxJobs = 8;
}
